#!/usr/bin/env ruby

require 'yaml'
require 'tty-command'

class Stack
  def self.setup(config)
    cmd = TTY::Command.new
    cmd.run('scripts/install-mysql.sh', config['mysql']['user'], config['mysql']['password'])
    cmd.run('scripts/install-postgresql.sh', config['postgresql']['user'], config['postgresql']['password'])
    cmd.run('scripts/install-php.sh')
    cmd.run('scripts/install-node.sh')
    cmd.run('scripts/install-nginx.sh')
    cmd.run('scripts/install-elasticsearch.sh', config['elasticsearch'])
    cmd.run('scripts/install-minio.sh', config['minio']['access_key'], config['minio']['secret_key'])
    cmd.run('scripts/install-cloud9.sh', config['cloud9']['access_key'], config['cloud9']['password'])
  end
  #{_x('./install-oh-my-zsh.sh')}

  def self.configure(config)
    # Create mysql databases
    if config['mysql'].key?('databases')
      config['mysql']['databases'].each do |db|
        %x(
          #{_x('./create-mysql-database.sh')} #{db} #{config['mysql']['user']} #{config['mysql']['password']}
        )
      end
    end

    # Create postgresql databases
    if config['postgresql'].key?('databases')
      config['postgresql']['databases'].each do |db|
        %x(
          #{_x('./create-postgresql-database.sh')} #{db} #{config['postgresql']['user']} #{config['postgresql']['password']}
        )
      end
    end

    config['sites'].each do |site|
      host = site['map']
      dir = site['to']
      php = site.fetch('php') { '' }

      %x(
        #{_x('./create-certificate.sh')} #{host}
        #{_x('./serve-laravel.sh')} #{host} #{dir} #{php}
      )
    end
  end

  def self._x(path)
    File.expand_path("../#{path}", __FILE__)
  end
end

def self.read_config
  path = File.expand_path('../../config/settings.yml', __FILE__)
  YAML.load_file(path)
end

args = ARGV
action = args.delete_at(0)

Stack.send(action.to_sym, read_config, *args)
